redis:
  image: redis

db:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: "password"
    POSTGRES_HOST_AUTH_METHOD: trust

vote:
  image: example-voting-app_vote
  ports:
    - 5000:80
  links:
    - redis

worker:
  image: example-voting-app_worker
  links:
    - redis
    - db

result:
  image: example-voting-app_result
  ports:
    - 5001:80
  links:
    - db
